ALTER TABLE Users DROP CONSTRAINT PK_Users;

ALTER TABLE Users
ADD CONSTRAINT PK_Person PRIMARY KEY([User Id]);

ALTER TABLE Users
ADD CONSTRAINT UC_Users UNIQUE([User Name]);

ALTER TABLE Users
ADD CONSTRAINT CHK_Users CHECK(LEN([User Password]) >= 3);